apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mssql-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
            - containerPort: 1433
          env:
          - name: MSSQL_PID
            value: "Express"
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
  - name: mssql
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mssql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433  
---
apiVersion : apps/v1
kind : Deployment
metadata:
  name: linkmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkmanagerservice
  template:
    metadata:
      labels:
        app: linkmanagerservice
    spec:
      containers:
        - name: linkmanagerservice
          image: margiran/linkmanagerapi:latest
          env:
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapi-clusterip-srvice
spec:
  type: ClusterIP
  selector:
    app: linkmanagerservice
  ports:
  - name: linkmanagerservice
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapinodeportservice-srv
spec:
  type: NodePort
  selector:
    app: linkmanagerservice
  ports:
    - name: linkmanagerservice
      protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapi-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: linkmanagerservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
