apiVersion : apps/v1
kind : Deployment
metadata:
  name: linkmanager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkmanagerservice
  template:
    metadata:
      labels:
        app: linkmanagerservice
    spec:
      containers:
        - name: linkmanagerservice
          image: margiran/linkmanagerapi:latest
          env:
          - name: DbSettings__Password
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: sa-password
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapi-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: linkmanagerservice
  ports:
  - name: linkmanagerservice
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapinodeportservice-srv
spec:
  type: NodePort
  selector:
    app: linkmanagerservice
  ports:
    - name: linkmanagerservice
      protocol: TCP
      port: 80
      targetPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapi-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: linkmanagerservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  