apiVersion: v1
kind: Service
metadata:
  name: linkmanagerapinodeportservice-srv
spec:
  type: NodePort
  selector:
    app: linkmanagerservice
  ports:
    - name: linkmanagerservice
      protocol: TCP
      port: 80
      targetPort: 80 